/**
 * AI Agent CLI 入口
 *
 * 提供命令行调用 AI 导读功能的能力。
 */

import { readFile, writeFile } from "fs/promises";
import { join } from "path";
import type { ProfileJSON } from "../types/profile";
import {
  narrateWithOpenAI,
  buildSystemPrompt,
  buildUserPrompt,
  compressProfileForAI,
  type NarrateOptions,
} from "./index";

export interface NarrateUserOptions {
  login: string;
  language?: "zh" | "en";
  style?: "professional" | "casual" | "brief";
}

/**
 * CLI: 为指定用户生成 AI 导读
 */
export async function narrateUser(options: NarrateUserOptions): Promise<void> {
  const { login, language = "zh", style = "professional" } = options;

  console.log(`[devhunt] 正在为用户 ${login} 生成 AI 导读...`);
  console.log(`[devhunt] 语言: ${language}, 风格: ${style}`);

  // 读取 profile.json
  const baseDir = join(process.cwd(), "out", login);
  const profilePath = join(baseDir, "profile.json");

  let profile: ProfileJSON;
  try {
    const content = await readFile(profilePath, "utf-8");
    profile = JSON.parse(content);
  } catch (err) {
    console.error(`[devhunt] 无法读取 ${profilePath}`);
    console.error(`[devhunt] 请先运行 'bun devhunt scan ${login}' 和 'bun devhunt report ${login}'`);
    throw err;
  }

  // 检查 API Key
  const apiKey = process.env.OPENAI_API_KEY;

  if (!apiKey) {
    // 没有 API Key，输出 prompt 供用户手动使用
    console.log("\n[devhunt] 未检测到 OPENAI_API_KEY 环境变量。");
    console.log("[devhunt] 将输出 prompt，您可以复制到 ChatGPT / Claude 等 LLM 中使用。\n");

    const systemPrompt = buildSystemPrompt({ language, style });
    const userPrompt = buildUserPrompt(profile);

    console.log("=".repeat(60));
    console.log("📋 System Prompt:");
    console.log("=".repeat(60));
    console.log(systemPrompt);
    console.log("\n" + "=".repeat(60));
    console.log("📋 User Prompt:");
    console.log("=".repeat(60));
    console.log(userPrompt);
    console.log("=".repeat(60));

    // 同时保存到文件
    const promptPath = join(baseDir, "narrate_prompt.txt");
    await writeFile(
      promptPath,
      `# System Prompt\n\n${systemPrompt}\n\n# User Prompt\n\n${userPrompt}`,
      "utf-8"
    );
    console.log(`\n[devhunt] Prompt 已保存到: ${promptPath}`);
    return;
  }

  // 有 API Key，调用 OpenAI
  console.log("[devhunt] 正在调用 OpenAI API...");

  try {
    const result = await narrateWithOpenAI(profile, apiKey, {
      language,
      style,
      baseUrl: process.env.OPENAI_BASE_URL,
      model: process.env.OPENAI_MODEL,
    });

    console.log("\n" + "=".repeat(60));
    console.log("🤖 AI 导读:");
    console.log("=".repeat(60));
    console.log(result.narrative);
    console.log("=".repeat(60));

    if (result.tokensUsed) {
      console.log(`\n[devhunt] Token 消耗: ${result.tokensUsed}`);
    }

    // 保存导读到文件
    const narrativePath = join(baseDir, "narrative.md");
    await writeFile(
      narrativePath,
      `# ${login} 开发者画像导读\n\n${result.narrative}\n\n---\n_Generated by DevHunt AI Agent_\n`,
      "utf-8"
    );
    console.log(`[devhunt] 导读已保存到: ${narrativePath}`);
  } catch (err) {
    console.error("[devhunt] AI 导读生成失败:", err);
    throw err;
  }
}
